#pragma config(Sensor, in1,    lineBoi,        sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonarFront,     sensorSONAR_inch)
#pragma config(Sensor, dgtl3,  sonarBack,      sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Moki|Baby

/* There is a bunch of function overloading here. That's when you make multiple functions with the same name.
*  Don't be alarmed! It's not witchcraft, and you don't need to know any witchcraft to use it.
*  Just call the version of the function that you want and you're good.
*  e.g. If you want to move forward at speed 5 for 5 seconds, call forward(5,5).
*  And If you want to just start moving forward at speed 5, call forward(5).
*/

void stop(int time) { // stop for some time
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(time);
}

void stop() { // just stop
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}

void forward(int speed, int time) { // move forward at some speed for some time
	motor[leftMotor] = speed;
	motor[rightMotor] = speed;
	wait1Msec(time);
}

void forward(int speed) { // just move forward
	motor[leftMotor] = -speed;
	motor[rightMotor] = -speed;
}

void backward(int speed, int time) { // move forward at some speed for some time
	motor[leftMotor] = -speed;
	motor[rightMotor] = -speed;
	wait1Msec(time);
}

void backward(int speed) { // just move forward
	motor[leftMotor] = -speed;
	motor[rightMotor] = -speed;
}

void turnLeft(int speed, int time) { // turn left at some speed for some time
	motor[leftMotor] = -speed;
	motor[rightMotor] = speed;
	wait1Msec(time);
}

void turnRight(int speed, int time) {
	motor[leftMotor] = speed;
	motor[rightMotor] = -speed;
	wait1Msec(time);
}
// i might make versions of these functions which take angle instead of speed/time, to streamline things

task main()
{
	int threshold = 500; // change this later based on actual black lines

	wait1Msec(2000); // wait 2 seconds before the program starts

	while(true)
	{
		int currentLineBoi = SensorValue[lineBoi];

		backward(24);

		// sensor sees line:
		if(SensorValue[lineBoi] > threshold)
		{
			turnLeft(32, 1000);
			stop(1000);
		}
	}

	while(SensorValue(sonarBack) > 2) // loop while ultrasonic sensor is > 20 inches away from something
	{
		motor[rightMotor] = -63; // Motor on port2 is run at half (63) power forward
		motor[leftMotor]  = -63; // Motor on povrt3 is run at half (63) power forward
	}
}
