#pragma config(Sensor, in1,    lineBoi,        sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonarFront,     sensorSONAR_inch)
#pragma config(Sensor, dgtl3,  sonarBack,      sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Moki|Baby

void stop(int time) {
	motor[leftMotor] = 0;
  motor[rightMotor] = 0;
  wait1Msec(time);
}

void forwardTime(int time) {
  motor[leftMotor] = 64;
  motor[rightMotor] = 64;
  wait1Msec(time);
}

void backwardTime(int time) {
  motor[leftMotor] = -64;
  motor[rightMotor] = -64;
  wait1Msec(time);
}

void turnLeft() {
  motor[leftMotor] = -64;
  motor[rightMotor] = 64;
  wait1Msec(1000);
}

void turnRight() {
  motor[leftMotor] = 64;
  motor[rightMotor] = -64;
  wait1Msec(500);
}

task main()
{
	int threshold = 2900; // change this later based on actual black lines

  wait1Msec(2000);

  while(true)
  {
    int currentLineBoi = SensorValue[lineBoi];

    motor[leftMotor]  = -64;
    motor[rightMotor] = -64;

    // sensor sees line:
    if(SensorValue(lineBoi) > threshold)
    {
      turnRight();
      stop(1000);
      wait1Msec(3000);
    }
  }

	while(SensorValue(sonarBack) > 2) // Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
	{
		motor[rightMotor] = -63; // Motor on port2 is run at half (63) power forward
		motor[leftMotor]  = -63; // Motor on povrt3 is run at half (63) power forward
	}
}
