#pragma config(Sensor, in1, lineFinder, sensorLineFollower)
#pragma config(Sensor, dgtl1, sonarFront, sensorSONAR_inch)
#pragma config(Motor, port2, rightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port3, leftMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor, port4, armMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port5, wristServo, tmotorServoStandard, openLoop)
#pragma config(Motor, port6, clawMotor, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This version of the main code is based on the pseudo-code on the autonomous' google doc. It will alternate from left side and right side of the field for the first 3 pipes. for the ast 3 pipes there is a special section of code at the end.

//TO DO:
// Turn pseudo code into real code
// Adjust values for actual playoff (requires field being finished).

#include "functions.c" // this is the file with all of the functions

task main()
{
  //SETUP
  stop();

  while(SensorValue[sonarFront] > 1) {} // wait until something is < 1" away

  int threshold = 3000; // change this later based on actual black lines

  int counter = 0; //for counting black lines.

  wait1Msec(1000); // wait 1 second before the program starts

  //Step 1: Start at the midpoint of the performance wall facing toward the train cars. Claw should be open.
  for (int N = 1; N <= 3; N++)
  {
    //Step 2: Get Nth pipe on left side
    //  A: Move backward.
    backward(30);
    //  B: At Nth detection of blackline apply pipePickUp(1).
    while (counter < N)
    {
      if (SensorValue[lineFinder] > threshold)
      {
        counter++;
      }
    }
    counter = 0;
    stop();
    pipePickUp(1);
    //Step 3: Place pipe on train cart.
    //  A: Move forward until ultrasonic sensor detects train cart.
    forward(30);
    while (SensorValue[sonarFront] < 5)
    {
    };
    stop();
    //  B: Rotate 90 degrees clockwise.
    turn(90);
    //  C: Move forward until blackline AND wall is detected.
    while (SensorValue[lineFinder] < threshold && SensorValue[sonarFront] > 14)
    {
      forward(30);
    }
    stop();
    //  D: Apply placeDownPipe(-1)(N).
    placePipeDown(-1, N);
    //  E: Rotate 90 degrees anticlockwise.
    turn(-90);
    //Step 4: Get Nth pipe on right side.
    //  A: Move backward.
    backward(30);
    //  B: At Nth detection of blackline apply pipePickUp(-1)
    while (counter < N)
    {
      if (SensorValue[lineFinder] > threshold)
      {
        counter++;
      }
    }
    counter = 0;
    stop();
    pipePickUp(-1);
    //Step 5:
    //  A: Move forward until ultrasonic sensor detects train cart.
    forward(30);
    while (SensorValue[sonarFront] < 5)
    {
    }
    stop();
    //  B: Rotate 90 degrees anticlockwise.
    turn(-90);
    //  C: Move forward until black line AND wall is detected.
    forward(30);
    while (SensorValue[lineFinder] < threshold && SensorValue[sonarFront] > 14)
    {
    }
    stop();
    //  D: Apply placePipeDown(1,N).
    placePipeDown(1, N);
    //  E: Rotate 90 degrees clockwise.
    turn(90);
    //Step 6: Repeat Steps 2-5 2 more times. (N++)
  }
  //Step 7: Get 4th pipe on left side.
  //  A: Move backward.
  backward(30);
  //  B: At 4th detection of backline apply pipePickUp(1).
  while (counter < 4)
  {
    if (SensorValue[lineFinder] > threshold)
    {
      counter++;
    }
  }
  counter = 0;
  stop();
  pipePickUp(1);
  //Step 8: Place left 4th pipe on MIDDLE train cart.
  //  A: Move forward until ultrasonic sensor detects train cart.
  while (SensorValue[sonarFront] < 5)
  {
    forward(30);
  };
  stop();
  //  B: Rotate 90 degrees clockwise.
  turn(90);
  //  C: Move forward until center line is detected.
  //FL
  forward(30);
  wait1Msec(1000);
  while (SensorValue[lineFinder] > threshold)
  {
  }
  stop();
  //  D: Apply placePipeDown(-1)(1).
  placePipeDown(-1, 1);
  //  E: Move forward until blackline AND wall is detected.
  forward(30);
  while (SensorValue[lineFinder] < threshold && SensorValue[sonarFront] > 14)
  {
  }
  stop();
  //  F: Rotate 90 degrees anticlockwise.
  turn(-90);
  //Step 9: Get 4th pipe on left side.
  //  A: Move backward.
  backward(30);
  //  B: At 4th detection of backline apply pipePickUp(-1).
  while (counter < 4)
  {
    if (SensorValue[lineFinder] > threshold)
    {
      counter++;
    }
  }
  counter = 0;
  stop();
  pipePickUp(-1);
  //Step 10: Place right 4th pipe on MIDDLE train cart.
  //  A: Move forward until ultrasonic sensor detects train cart.
  forward(30);
  while (SensorValue[sonarFront] < 5)
  {
  };
  stop();
  //  B: Rotate 90 degrees anticlockwise.
  turn(-90);
  //  C: Move forward until center line is detected.
  //FL
  forward(30);
  wait1Msec(1000);
  while (SensorValue[lineFinder] > threshold)
  {
  }
  stop();
  //  D: Apply placePipeDown(-1)(2).
  placePipeDown(-1, 2);
  //  E: Rotate 90 degrees anticlockwise.
  turn(-90);
  //Step 11:
  //  A: Move forward until ultrasonic sensor detects pipe.
  forward(30);
  while (SensorValue[sonarFront] > 3)
  {
  }
  stop();
  //  B: Close claw now holding the pipe.
  setClawState('c');
  //  C: Go backwards for a bit.
  backward(30, 1000);
  //  D: Rotate 180 degrees.
  turn(-180);
  //  E: Move forward until ultrasonic sensor detects MIDDLE train cart.
  forward(30);
  while (SensorValue[sonarFront] < 5)
  {
  };
  stop();
  //  F: Apply placePipeDown(0)(3)
  placePipeDown(0, 3);
};

//Function to pick up a pipe from anyside of the robot. 1 for rightside. -1 for leftside. 0 for front and 2 or -2 for backside. This code will also return the robot to its position before the function was applied.
void pipePickUp(int direction) //direction is for where the pipe/train cart is relative to the robot. -2 = behind the robot. -1 = left of the robot. 0 = front of the robot. 1 = right of the robot.
{
  //A: Move forward until robot's center of rotation is inline with the pipe.
  forward(15, 1000); //ADJUST
  //B: Turn 90*direction degrees clockwise.
  turn(90 * direction);
  //C: Move forward until ultrasonic sensor detects pipe. Save time taken.
  ClearTimer(T1);
  while (SensorValue[sonarFront] > 3)
  {
    forward(20);
  }
  int timeTaken = time1[T1];
  stop();
  //D: Close claw nowholding the pipe.
  setClawState('c');
  //E: Move backward for time taken.
  backward(20, timeTaken);
  //F: Turn 90*direction degrees counterclockwise.
  turn(-90 * direction);
}

void placePipeDown(int direction, int position) //1 = back of train cart. 2 = front of train cart. 3 = top of train cart.
//Notes:
//- -27 degrees for 1 and 2. -17 degrees for 3.
//- may be better to let go by turning instead of backing away for 3.
{
  backward(30 * direction, 1000); //Adjust time.
  turn(90 * direction);
  int angle = 0;
  int length = 0;
  switch (position)
  {
  case 1:
    angle = -27;
    length = 2500; //Adjust
    break;

  case 2:
    angle = -27;
    length = 2000; //Adjust
    break;

  case 3:
    angle = -17;
    length = 2250;
    break;
  }
  turnClaw(-90);
  forward(15, length);
  moveArm(angle);
  setClawState('o');
  backward(15, length);
  moveArm(angle);
  turn(-90 * direction);
  forward(30 * direction, 1000); //Adjust time.
  turnClaw(90);
}
